// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type User struct {
	ID        int64
	Username  string
	Password  string
	ApiKey    interface{}
	UpdatedAt sql.NullString
}
