// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, password, api_key)
VALUES (?, ?, ?)
`

type CreateUserParams struct {
	Username string
	Password string
	ApiKey   interface{}
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Username, arg.Password, arg.ApiKey)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByApikeys = `-- name: GetUserByApikeys :one
SELECT id, username, password, api_key, updated_at FROM users WHERE api_key = ?
`

func (q *Queries) GetUserByApikeys(ctx context.Context, apiKey interface{}) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByApikeys, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.ApiKey,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, api_key, updated_at FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.ApiKey,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE users
SET api_key = ?, updated_at = CURRENT_TIMESTAMP
WHERE username = ?
`

type UpdateAPIKeyParams struct {
	ApiKey   interface{}
	Username string
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKey, arg.ApiKey, arg.Username)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = ?, updated_at = CURRENT_TIMESTAMP 
WHERE username = ?
`

type UpdateUserPasswordParams struct {
	Password string
	Username string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.Username)
	return err
}
